[package]
name = "oauthcli"
version = "1.0.2"
authors = ["azyobuzin <azyobuzin@users.sourceforge.jp>"]
description = "Implementation of OAuth 1.0 (and Twitter's f*ckin' OAuth) Client"
documentation = "https://docs.rs/oauthcli/1.0.2/oauthcli/"
repository = "https://github.com/azyobuzin/rust-oauthcli"
readme = "README.md"
keywords = ["oauth"]
license = "MIT/Apache-2.0"

[dependencies]
rand = "0.3"
rust-crypto = "0.2"
rustc-serialize = "0.3"
time = "0.1"
url = "1.2"
hyper = { version = "0.9", default-features = false, optional = true }
