[package]
name = "oauthcli"
version = "1.0.0"
authors = ["azyobuzin <azyobuzin@users.sourceforge.jp>"]
description = "Implementation of OAuth 1.0 Client without curl dependency"
documentation = "http://azyobuzin.github.io/rust-oauthcli/oauthcli/"
repository = "https://github.com/azyobuzin/rust-oauthcli"
keywords = ["oauth"]
license = "MIT"

[dependencies]
rand = "0.3"
rustc-serialize = "0.3"
time = "0.1"
url = "1.2"
hyper = { version = "0.9", optional = true }
